### ISSUE TITLE
`client.play_by_play` failing with `ValueError: time data 'Time' does not match format '%M:%S.%f'`

### ISSUE THREAD

**Issue by germannp** [jaebradley/basketball_reference_web_scraper#229]
Hello,

I am running into this `ValueError: time data 'Time' does not match format '%M:%S.%f'` error with `client.play_by_play`:

```
Traceback (most recent call last):
...
    client.play_by_play(
  File "...\basketball_reference_web_scraper\client.py", line 220, in play_by_play
    values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)
  File "...\basketball_reference_web_scraper\http_service.py", line 104, in play_by_play
    return self.parser.parse_play_by_plays(
  File "...\basketball_reference_web_scraper\parser_service.py", line 92, in parse_play_by_plays
    return self.play_by_plays_parser.parse(
  File "...\basketball_reference_web_scraper\parsers.py", line 541, in parse
    result.append(self.format_data(
  File "...\basketball_reference_web_scraper\parsers.py", line 553, in format_data
    "remaining_seconds_in_period": self.period_timestamp_parser.to_seconds(timestamp=play_by_play.timestamp),
  File "...\basketball_reference_web_scraper\parsers.py", line 157, in to_seconds
    dt = datetime.strptime(timestamp, self.timestamp_format)
  File "C:\ProgramData\Anaconda3\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\ProgramData\Anaconda3\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Time' does not match format '%M:%S.%f'
```
Any ideas?

I assume this started around February 17th, however it won't work with previous dates neither.

Thank you!

**Comment by sdm373373** [comment]
I'm having the same issue

**Comment by germannp** [comment]
To me it look like this package is no longer maintained: they don't even bother fixing links to the wrong package in the docs (see #227). On the bright side, this "wrong" package works, looks very much alive, and also scraps shot charts; so I guess it's time to move on to https://github.com/vishaalagartha/basketball_reference_scraper/blob/master/API.md :-)

**Comment by tttgm** [comment]
I've submitted a pull request for this issue here: [PR-230](https://github.com/jaebradley/basketball_reference_web_scraper/pull/230)

Not sure if the repo is still maintained though as you said.

**Comment by jaebradley** [comment]
Apologies for the delay in responding to this issue. This project has been (effectively) unmaintained for a few years. I'm circling back to feature requests and open issues.

For this specific issue, [as mentioned on the fix PR referenced in this issue](https://github.com/jaebradley/basketball_reference_web_scraper/pull/324#issuecomment-4854532231), I don't think this is a problem at the moment.

Feel free to re-open this issue if this continues to be a problem. Apologies again for the delay in responding.
