### ISSUE TITLE
Unable to get stats for current season

### ISSUE THREAD

**Issue by AnkitPatanaik** [jaebradley/basketball_reference_web_scraper#52]
When trying to make a call getting data for the current season (season ending in 2019), I receive the following error:

```
Traceback (most recent call last):
  File "compare.py", line 25, in <module>
    print(get_stats(get_values(["Joe Harris", "Kevin Durant"])))
  File "compare.py", line 8, in get_values
    players = client.players_season_totals(2019)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/basketball_reference_web_scraper/client.py", line 35, in players_season_totals
    values = http_client.players_season_totals(season_end_year)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/basketball_reference_web_scraper/http_client.py", line 66, in players_season_totals
    return parse_players_season_totals(response.content)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/basketball_reference_web_scraper/parsers/players_season_totals.py", line 43, in parse_players_season_totals
    totals.append(parse_player_season_totals(row))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/basketball_reference_web_scraper/parsers/players_season_totals.py", line 9, in parse_player_season_totals
    "position": POSITION_ABBREVIATIONS_TO_POSITION[row[2].text_content()],
KeyError: 'F-G'```

**Comment by jaebradley** [comment]
@AnkitPatanaik thanks for reporting this issue

It looks like Basketball Reference added the `F-G` position value for Jimmy Butler's Philadelphia 76ers season totals.

![image](https://user-images.githubusercontent.com/8136030/48657812-b51d9000-e9eb-11e8-8fa9-db78a1d9d5d6.png)

This is the first time I've seen this position value used for a player's season totals (usually, the multi-position values are used when a player has played multiple positions across multiple teams).

#53 should fix this.

**Comment by AnkitPatanaik** [comment]
Awesome! Thanks a lot :)

**Comment by jaebradley** [comment]
@AnkitPatanaik After installing `v3.1.1`, I hope your issue has been resolved. Please re-open if that's not the case.

**Comment by AnkitPatanaik** [comment]
Hey @jaebradley, I tried install version 3.1.1 but pip was unable to find the updated version. Maybe I'm doing something wrong?

```
~/dev/fantasy-bball(branch:master*) » pip install basketball_reference_web_scraper==3.1.1
Collecting basketball_reference_web_scraper==3.1.1
  Could not find a version that satisfies the requirement basketball_reference_web_scraper==3.1.1 (from versions: 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1)
No matching distribution found for basketball_reference_web_scraper==3.1.1
```

**Comment by AnkitPatanaik** [comment]
It looks like there are some other positions that are not accounted for:

```
Traceback (most recent call last):
  File "compare.py", line 40, in <module>
    main()
  File "compare.py", line 37, in main
    team1_players = get_values(team_1)
  File "compare.py", line 11, in get_values
    players = client.players_season_totals(YEAR_END)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/basketball_reference_web_scraper/client.py", line 35, in players_season_totals
    values = http_client.players_season_totals(season_end_year)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/basketball_reference_web_scraper/http_client.py", line 66, in players_season_totals
    return parse_players_season_totals(response.content)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/basketball_reference_web_scraper/parsers/players_season_totals.py", line 43, in parse_players_season_totals
    totals.append(parse_player_season_totals(row))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/basketball_reference_web_scraper/parsers/players_season_totals.py", line 9, in parse_player_season_totals
    "position": POSITION_ABBREVIATIONS_TO_POSITION[row[2].text_content()],
KeyError: 'F'
```

I would presume there might be combinations like "F-C" and "G" as well but I am yet to confirm
