### ISSUE TITLE
It looks like there are some other positions that are not accounted for:

### ISSUE THREAD

**Issue by AnkitPatanaik** [jaebradley/basketball_reference_web_scraper#54]
```
Traceback (most recent call last):
  File "compare.py", line 40, in <module>
    main()
  File "compare.py", line 37, in main
    team1_players = get_values(team_1)
  File "compare.py", line 11, in get_values
    players = client.players_season_totals(YEAR_END)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/basketball_reference_web_scraper/client.py", line 35, in players_season_totals
    values = http_client.players_season_totals(season_end_year)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/basketball_reference_web_scraper/http_client.py", line 66, in players_season_totals
    return parse_players_season_totals(response.content)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/basketball_reference_web_scraper/parsers/players_season_totals.py", line 43, in parse_players_season_totals
    totals.append(parse_player_season_totals(row))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/basketball_reference_web_scraper/parsers/players_season_totals.py", line 9, in parse_player_season_totals
    "position": POSITION_ABBREVIATIONS_TO_POSITION[row[2].text_content()],
KeyError: 'F'
```

I would presume there might be combinations like "F-C" and "G" as well but I am yet to confirm.

_Originally posted by @AnkitPatanaik in https://github.com/jaebradley/basketball_reference_web_scraper/issues/52#issuecomment-439639601_

**Comment by jaebradley** [comment]
@AnkitPatanaik what season(s) are causing this issue?

**Comment by AnkitPatanaik** [comment]
2019
