### ISSUE TITLE
Certifi Conflict

### ISSUE THREAD

**Issue by evanagovino** [jaebradley/basketball_reference_web_scraper#87]
Having issues installing this because of a conflict with 'Certifi':

  Found existing installation: certifi 2019.6.16
    Uninstalling certifi-2019.6.16:
Exception:
Traceback (most recent call last):
  File "/Users/evan.agovino/anaconda3/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/Users/evan.agovino/anaconda3/lib/python3.6/site-packages/certifi-2019.6.16.dist-info/DESCRIPTION.rst' -> '/var/folders/lk/zxfkkcj155d51dt9l80yrdfhfbznt_/T/pip-qttxhug1-uninstall/Users/evan.agovino/anaconda3/lib/python3.6/site-packages/certifi-2019.6.16.dist-info/DESCRIPTION.rst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/evan.agovino/anaconda3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/evan.agovino/anaconda3/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Users/evan.agovino/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Users/evan.agovino/anaconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Users/evan.agovino/anaconda3/lib/python3.6/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Users/evan.agovino/anaconda3/lib/python3.6/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/Users/evan.agovino/anaconda3/lib/python3.6/shutil.py", line 565, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/Users/evan.agovino/anaconda3/lib/python3.6/site-packages/certifi-2019.6.16.dist-info/DESCRIPTION.rst'

**Comment by jaebradley** [comment]
@evanagovino What version are you using / installing?

For reference this `repl.it` seems to install the latest client without issues: https://repl.it/@jaebradley/2019-season-totals

**Comment by evanagovino** [comment]
My version is certifi==2019.6.16. when I changed the setup.py from "certifi==2018.10.15" to "certifi>=2018.10.15" it worked for me

**Comment by jaebradley** [comment]
@evanagovino do you have an open-source repository / code sample to show your setup?

**Comment by evanagovino** [comment]
Seems to work in a virtual environment: https://repl.it/@evanagovino/SilverPlushCircle

The issue is the same as [here]('https://github.com/InstaPy/instapy-quickstart/issues/46'), where the install will fail on a machine with multiple users where a different version Certifi is already installed. The pip install will work with a user flag, in a virtual environment setup or with a sudo pip install, but will fail otherwise. Not a huge deal but maybe worth noting in the README if other people are having similar issues

**Comment by jaebradley** [comment]
@evanagovino I think I might need to be less restrictive (i.e. `>=`) about the requirements defined in `requirements.txt`.

I'll try and get something out.

Thanks for surfacing this issue 👍 !
